# Generated by Django 4.2 on 2023-04-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='action',
            name='actions_act_target__253c91_idx',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='target_pk',
            new_name='target_id',
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['target_ct', 'target_id'], name='actions_act_target__f20513_idx'),
        ),
    ]
